theme: jekyll-theme-minimal
# Site settings
title: You Blog    				  	#你博客的标题
SEOTitle: 你的博客 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: lyzcgx@163.com	
description: "You Blog"  			 #网站介绍
keyword: "zhuchenguang,朱晨光，programming,computer science" #关键词
url: "https://zhezcg.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description:"programming for fun！"            #描述
